### ISSUE TITLE
Setting as default SMS

### ISSUE THREAD

**Issue by PixelBit92** [ngreenan/p5imapp#2]
I can't seem to get it to set as default. Pressing the button in the app doesn't do anything, and it's not an option when I try to set it in the settings app, and since that button covers the box for making texts, I can't do that

**Comment by ngreenan** [comment]
I'm assuming that you're using Android 10 or newer? If so, that's expected behaviour as it hasn't been updated to be compatible with Android 10. I'm no longer working on the app so this won't be fixed either, sorry!
