### ISSUE TITLE
Default App

### ISSUE THREAD

**Issue by MrCamel999** [ngreenan/p5imapp#3]
App won't let me make it the default messaging app. Both through the app itself or the settings. Using Samsung Galaxy S10+ if that helps on the latest software.

**Comment by ngreenan** [comment]
If you're running Android 10 or newer then this is expected - Google changed something in terms of what's needed to set an app as default. Suspect that you're on Android 10 as I used to have an S10 and the latest version was 10, had the same issue. 

As I'm no longer working on this app (this repo is solely here to host the apk) then this won't be fixed, so I'm going to close this issue. Sorry!
